@AzElevator.AzureAIHandsOn_HostAddress = http://localhost:5236

POST {{AzElevator.AzureAIHandsOn_HostAddress}}/ask/
Accept: application/json
Content-Type: application/json 

{
"query" : "Quelles sont les phases du cycle de vie d'une entreprise?"
}

###

POST {{AzElevator.AzureAIHandsOn_HostAddress}}/marketer?llm=local
Accept: application/json
Content-Type: application/json

{
  "query" : "Tu peux me rédiger un article sur la relation entre TDD et l'utilisation de l'IA ?"
}

###
